name: EC2 CD Pipeline on AWS
on:
  workflow_run:
    workflows: ["Build Docker images"]
    types:
      - completed
jobs:
  ec2-cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - name: Copy required files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "docker/docker-compose.prod.yml, docker-compose.yml, deployment/*"
          target: "/home/ubuntu/dev/investpulse"
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/dev/investpulse/deployment
            make up-recreate-app TAG_VERSION=${{ github.event.workflow_run.head_branch }}
