name: Check Version and Release

on:
  push

permissions:
  contents: write

jobs:
  check_version:
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.ref, '/develop') || endsWith(github.ref, '/main') || startsWith(github.ref, 'refs/tags')}}
    steps:
      - uses: actions/checkout@v4
      - name: Check Version
        uses: ./.github/release-action

  release:
    name: Release pushed tag
    needs: check_version
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
#        uses: ./.github/release-action
#        with:
#          create-release: true
#          tag: ${{ github.ref_name }}
